### ISSUE TITLE
Criar mini Banner

### ISSUE THREAD

**Issue by elianemaciel** [PyladiesCaxias/organization#1]
(Pode ser só a imagem depois vemos para fazer a impressão)
Tamanho  pode ser A4 (colorido) colocar o nome site, email e facebook.
Talvez uma mini descrição.
Colocar nos murais das Faculdades e escolas

**Comment by elianemaciel** [comment]
@mcwplima, @jaquelinetrevizan  Vamos criar um doc para este banner? Aí vamos trabalhando em conjunto. Depois fazemos a impressão em folha colorida e divulgamos nas Universidades e escolas.

**Comment by ghost** [comment]
Sim, podemos fazer um poster simples mas que chame a atenção.
