### ISSUE TITLE
Camisetas/Bottons

### ISSUE THREAD

**Issue by elianemaciel** [PyladiesCaxias/organization#2]
Conversamos no dia 18/11 da possibilidade de fazer camisetas do PyLadies Caxias do Sul. Temos que ver quem quer fazer, modelos, valores.

**Comment by elianemaciel** [comment]
@mcwplima Você consegue montar um layout de camiseta para nós? Depois te ajudo a ver orçamentos.

**Comment by elianemaciel** [comment]
- [x] Layout Camisetas
- [ ] Orçamentos

- [x] Layout Bottons

- [ ] Orçamento Bottons

**Comment by elianemaciel** [comment]
## Camisetas

- [ ] Proposta 1 - Roxa com logo grande  na frente.
[banner.pdf](https://github.com/PyladiesCaxias/organization/files/1656004/banner.pdf)
![banner](https://user-images.githubusercontent.com/7025421/35277477-a9ded614-0025-11e8-84ef-cb138fb3bd87.png)

- [ ] Proposta 2 - Branca com logo grande na frente.  (Logo padrão, só tem que ajustar para a carinha ficar maior)

**Comment by elianemaciel** [comment]
## Bottons

Acho que os bottons podem ser iguais aos adesivos

**Comment by ghost** [comment]
Gostei da sugestão da camiseta roxa :)
Tenho ideia de um local para orçarmos as camisetas!

**Comment by elianemaciel** [comment]
Beleza! Precisamos de um lugar que faça um bom valor. Podemos até fazer as camisetas dos outros eventos lá também. Os lugares que conheço está caro!

**Comment by ghost** [comment]
Você chegou a orçar na Pakuá Sport http://www.pakuasport.com/?

**Comment by elianemaciel** [comment]
Não vi com eles, podemos ver sim! Sábado decidimos isso.

**Comment by ghost** [comment]
Organização do almoço para arrecadar recursos para eventos e caixinha.
